spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: ${MONGO_URI}

app:
  jwtSecret: ${JWT_KEY}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${email}
  password: ${email.key}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true