spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: ${MONGO_URI}

app:
  jwtSecret: ${JWT_KEY}

email:
  spring.mail.host: smtp.gmail.com
  spring.mail.port: 587
  spring.mail.username: ${EMAIL}
  spring.mail.password: ${EMAIL_KEY}
  spring.mail.properties.mail.smtp.auth: true
  spring.mail.properties.mail.smtp.starttls.enable: true