spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: ${MONGO_URI}

app:
  jwtSecret: ${JWT_KEY}

email:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL}
  password: ${EMAIL_KEY}
  properties:
    email:
      smtp:
        auth: true
        starttls:
          enable: true